name: Create Cloud Infra
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCOUNT_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCOUNT_SECRET }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
jobs:
   iac:
     runs_on: ubuntu-latest
     steps:
     - name: checkout the code
       uses: actions/checkout@v6
     - name: setup terraform 
       uses: hashicorp/setup-terraform@v4
     - name: Create infra 
       run: |
         ls -lart
         terraform init
         terraform apply --auto-aprove         
          
  
  